apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::903180158771:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-Mrxyi5Sn32GH
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::903180158771:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-10-30T21:08:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1364"
  uid: 9f9a4ad0-f0cf-48c5-9a1c-ee1b595741eb
